version: '3.4'

services:
  tgpro:
    image: ${DOCKER_REGISTRY-}tgpro
    build:
      context: .
      dockerfile: src/API/Dockerfile
    environment:
      - "ConnectionStrings__DefaultConnection=Server=db;Database=tgpro;User=sa;Password=P@ssw0rd1;MultipleActiveResultSets=true"
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=P@ssw0rd1"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
    restart: on-failure
    container_name: tgpro

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "SA_PASSWORD=P@ssw0rd1"
      - "ACCEPT_EULA=Y"
    ports:
      - "1433:1433"
    container_name: mssql
